apiVersion: v1
kind: Service
metadata:
  name: keyvault-demo
  namespace: keyvault-demo
spec:
  type: LoadBalancer
  selector:
    app: keyvault-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
